<?php
// One-time setup: creates .user.ini and .htaccess entries so PHP can
// write upload temp files inside this hosting account.
// Visit this page once, verify "Done", then DELETE this file.

$root   = __DIR__;
$tmpDir = $root . '/storage/tmp';

$steps = [];

// 1. Ensure the tmp directory exists and is writable
if (!is_dir($tmpDir)) {
    mkdir($tmpDir, 0755, true);
}
chmod($tmpDir, 0755);
$steps[] = is_writable($tmpDir)
    ? "✓ storage/tmp is writable ($tmpDir)"
    : "✗ storage/tmp is NOT writable — chmod 755 it in cPanel";

// 2. Write .user.ini (PHP-FPM / CGI FastCGI)
$userIni = $root . '/.user.ini';
$iniContent = "; Auto-generated by setup-tmp.php\n"
            . "upload_tmp_dir = \"$tmpDir\"\n"
            . "sys_temp_dir   = \"$tmpDir\"\n";

if (file_put_contents($userIni, $iniContent) !== false) {
    $steps[] = "✓ .user.ini written";
} else {
    $steps[] = "✗ Could not write .user.ini — check directory permissions";
}

// 3. Append to root .htaccess (Apache mod_php fallback)
$htaccess = $root . '/.htaccess';
$htLine   = "\nphp_value upload_tmp_dir \"$tmpDir\"\nphp_value sys_temp_dir  \"$tmpDir\"\n";
$existing = file_exists($htaccess) ? file_get_contents($htaccess) : '';
if (strpos($existing, 'upload_tmp_dir') === false) {
    file_put_contents($htaccess, $existing . $htLine);
    $steps[] = "✓ .htaccess updated with upload_tmp_dir";
} else {
    $steps[] = "✓ .htaccess already contains upload_tmp_dir (skipped)";
}

echo "<pre style='font-family:monospace;font-size:14px;padding:20px'>";
echo "Upload Temp Dir Setup\n";
echo str_repeat('─', 50) . "\n\n";
echo "Temp path: $tmpDir\n\n";
foreach ($steps as $s) echo $s . "\n";
echo "\n" . str_repeat('─', 50) . "\n";
echo "Done. Delete this file (setup-tmp.php) from the server.\n";
echo "\nNote: .user.ini changes may take up to 5 minutes to take effect\n";
echo "(PHP-FPM caches user ini files). Try uploading after ~5 min.\n";
echo "</pre>";
